config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :foods
  
  resources :recipes, except: [:update] do
    member do
      patch :toggle_public
    end
    resources :recipe_foods, only: [:new, :create]
  end
  
  resources :recipe_foods, except: [:new, :create]

  delete 'foods/:id', to: 'foods#destroy', as: 'delete_food'
  get 'public_recipes', to: 'public_recipes#index'
  get 'shopping_list', to: 'shopping_lists#index'
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods
  validates :name, presence: true
  def total_price
    recipe_foods.sum { |rf| rf.quantity * rf.food.price }
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
  validates :quantity, presence: true, numericality: { greater_than: 0 }
  after_create :decrease_food_quantity
  before_update :store_previous_quantity
  after_update :update_food_quantity_after_edit
  before_destroy :return_food_quantity

  attr_accessor :previous_quantity

  private

  def decrease_food_quantity
    food.update(quantity: food.quantity - quantity)
  end

  def store_previous_quantity
    self.previous_quantity = quantity_was
  end

  def update_food_quantity_after_edit
    difference = previous_quantity - quantity
    food.update(quantity: food.quantity + difference)
  end

  def return_food_quantity
    food.update(quantity: food.quantity + quantity)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods
  has_many :recipes

  # validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_current_user

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email password current_password])
  end

  private

  def set_current_user
    @user = current_user
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @user = current_user
    @foods = Food.includes(:user).where(user_id: @user.id)
  end

  def new
    @user = current_user
    @food = Food.new
  end

  def create
    @user = current_user
    @food = Food.new(food_params)
    @food.user_id = @user.id
    if @food.save
      redirect_to foods_path
    else
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @user = current_user
    @public_recipes = Recipe.where(public: true)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe_food = RecipeFood.new
    @available_foods = available_foods_for_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    if @recipe_food.save
      redirect_to @recipe_food.recipe, notice: 'Ingredient added successfully.'
    else
      render :new
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    redirect_to recipe_path(@recipe_food.recipe), notice: 'Ingredient was successfully removed.'
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
    @available_foods = Food.includes(:user).where(user_id: current_user.id)
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.update(recipe_food_params)
      redirect_to @recipe_food.recipe, notice: 'Ingredient quantity was successfully updated.'
    else
      render :edit
    end
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:recipe_id, :food_id, :quantity)
  end

  def available_foods_for_recipe
    # Get the foods that are not used in the current recipe
    recipe = Recipe.find(params[:recipe_id])
    used_food_ids = recipe.recipe_foods.pluck(:food_id)
    Food.includes(:user).where(user_id: current_user.id).where.not(id: used_food_ids)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
    @recipes = current_user.recipes.includes(:foods, :recipe_foods)
  end

  def show
    @user = current_user
    @recipe = Recipe.includes(:foods, :recipe_foods).find(params[:id])
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.user == current_user
      @recipe.destroy
      redirect_to recipes_path, notice: 'Recipe was successfully deleted.'
    else
      redirect_to recipes_path, alert: 'You are not authorized to delete this recipe.'
    end
  end

  def new
    @user = current_user
    @recipe = current_user.recipes.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe successfully created!'
    else
      render :new
    end
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public) if @recipe.user == current_user
    redirect_to @recipe
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def index
    @user = current_user
    @shopping_list = calculate_shopping_list
  end

  private

  def calculate_shopping_list
    shopping_list = {}
    total_value = 0
    total_items = 0

    @user.foods.each do |food|
      next unless food.quantity.negative?

      quantity_needed = -food.quantity
      total_value += quantity_needed * food.price
      total_items += 1
      shopping_list[food.name] = { quantity: quantity_needed, price: food.price }
    end

    {
      shopping_list:,
      total_value:,
      total_items:
    }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.includes(:foods, :recipes).find(params[:id])
  end

  def new
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/views/foods/index.html.erb
<%# path: app/views/foods/index.html.erb %>

<%= link_to 'Add Food', new_food_path, class:"btn" %>
<% if @foods.size > 0%>
  <table>
    <thead>
      <tr class="tr-head">
        <th>Food</th>
        <th>Measurement unit</th>
        <th>Unit price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr class="tr-list li">
          <td class="food-name"><%= food.name %></td>
          <td class="food-measurement-unit"><%= food.measurement_unit %></td>
          <td class="food-price">$ <%= food.price %></td>
          <td>
            <%= form_for food, method: :delete, url: food_path(food) do |f| %>
              <%= f.submit "Delete", class:"btn" %>
            <% end %>
          </td>            
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="p-no-foods">There are no foods</p>
<% end %>

app/views/foods/new.html.erb
<%# path: app/views/foods/new.html.erb %>

<%= form_for @food do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :measurement_unit %>
    <%= f.select :measurement_unit, options_for_select(['ounces', 'pounds', 'grams', 'kilograms', 'liters', 'gallons', 'units'], 'units') %>
  </p>
  <p>
    <%= f.label :price %>
    <%= f.number_field :price %>
  </p>
  <p>
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </p>
  <%= f.submit class:"btn"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render partial: "shared/navbar" %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="yield">
      <%= yield %>
    </div>
  </body>
</html>

app/views/public_recipes/index.html.erb
<%# path: app/views/public_recipes/index.html.erb %>

<h2>Public recipes</h2>

<ul class="recipes-index-ul">
  <% @public_recipes.each do |pr| %>
    <li class="li">
      <div class="left">
        <p class="pr-name"><%= link_to pr.name, recipe_path(pr) %></p>
        <p class="pr-user-name">By: <%= pr.user.name %></p>
      </div>
      <div class="recipe-description">
        <p class="pr-recipe-foods-count">Total food items: <%= pr.recipe_foods.count %></p>
        <p class="pr-total-price">Total price: $ ... <%= pr.total_price %></p>
      </div>
    </li>
  <% end %>
<ul>

app/views/recipe_foods/edit.html.erb
<%# path: app/views/recipe_foods/edit.html.erb %>

<h2>Edit Ingredient Quantity for <%= @recipe_food.recipe.name %></h2>

<%= form_with(model: @recipe_food, url: recipe_food_path(@recipe_food), method: :patch) do |form| %>
  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, step: 0.1 %>
  </div>

  <div class="actions">
    <%= form.submit "Update Ingredient", class: 'btn' %>
  </div>
<% end %>

app/views/recipe_foods/new.html.erb
<%# path: app/views/recipe_foods/new.html.erb %>

<%= form_with(model: @recipe_food, url: recipe_recipe_foods_path(@recipe)) do |f| %>
  <%= f.hidden_field :recipe_id, value: @recipe.id %>

  <div>
    <%= f.label :food_id, 'Select Food' %>
    <%= f.collection_select :food_id, @available_foods, :id, 
  lambda { |food| "#{food.name} (Available: #{food.quantity})" } %>
  </div>

  <div>
    <%= f.label :quantity, 'Quantity' %>
    <%= f.number_field :quantity, min: 0 %>
  </div>

  <div>
    <%= f.submit 'Add Ingredient', class: 'btn' %>
  </div>
<% end %>

app/views/recipes/index.html.erb
<%# path: app/views/recipes/index.html.erb %>

<%= link_to "Add New Recipe", new_recipe_path, class: "add-new-recipe btn" %>
<ul class="recipes-index-ul">
  <% @recipes.each do |recipe| %>
    <li class="recipes-index-li li">
      <div class="left">
        <%= link_to recipe.name, recipe_path(recipe), class:"recipe-name btn" %> 
        <% if recipe.user == current_user %>
          <%= button_to 'Remove', recipe_path(recipe), method: :delete, class:"remove btn" %>
        <% end %>
      </div>
      <p class="recipe-description"><%= recipe.description %></p>
    </li>
  <% end %>
</ul>

app/views/recipes/new.html.erb
<%# path: app/views/recipes/new.html.erb %>

<h1>Add New Recipe</h1>

<%= form_for @recipe do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :preparation_time %>
    <%= f.number_field :preparation_time, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :cooking_time %>
    <%= f.number_field :cooking_time, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :public %>
    <%= f.check_box :public, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Add Recipe", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/recipes/show.html.erb
<%# path: app/views/recipes/show.html.erb %>

<h1><%= @recipe.name %></h1>
<p>Preparation Time: <%= @recipe.preparation_time %></p>
<p>Cooking Time: <%= @recipe.cooking_time %></p>

<!-- Toggle button for public/private status -->
<% if @recipe.user == current_user %>
  <%= form_with(url: toggle_public_recipe_path(@recipe), method: :patch) do %>
    <div class="public-toggle">
      Public:
      <%= check_box_tag :public, 1, @recipe.public, onchange: 'this.form.submit()' %>
    </div>
  <% end %>
<% else %>
  <p>Public: <%= @recipe.public ? 'Yes' : 'No' %></p>
<% end %>

<h3>Steps:</h3>
<p>Steps go here...</p>
<% if @recipe.user == current_user %>
  <%= link_to 'Add ingredient', new_recipe_recipe_food_path(@recipe), class: 'btn btn-primary' %>
<% end%>
<%= link_to "Shopping List", shopping_list_path %>
<!-- Foods / Ingredients for the Recipe -->
<h3>Ingredients:</h3>
<table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @recipe.recipe_foods.each do |recipe_food| %>
    <tr>
    <td><%= recipe_food.food.name %></td>
    <td><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %></td>
    <td>$<%= recipe_food.food.price %></td>
    <td>
    <% if @recipe.user == current_user %>
    <%= link_to 'Modify', edit_recipe_food_path(recipe_food), class: 'btn btn-primary' %>
    <%= button_to 'Remove', recipe_food_path(recipe_food), method: :delete, data: { confirm: '¿Are you sure you want to delete this ingredient?' }, class: 'btn btn-danger' %>
   <% end %>
    </td>
  </tr>

    <% end %>
  </tbody>
</table>

app/views/shared/_navbar.html.erb
<%# path: app/views/shared/_navbar.html.erb %>

<nav>
  <div>
    <%= image_tag("hero.png", alt: "A bowl and a mixer logo for the Recipes App", class: "navbar-image") %>
    <h1>Welcome <%= @user.name %> </h1>
  </div>
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Foods", foods_path %></li>
    <li><%= link_to "Recipes", recipes_path %></li>
    <li><%= link_to "Public Recipes", public_recipes_path %></li>
    <li><%= link_to "Shopping List", shopping_list_path %></li>
    <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %></li>
  </ul>
</nav>

app/views/shopping_lists/index.html.erb
<%# path: app/views/shopping_lists/index.html.erb %>

<h1>Shopping List</h1>

<p class="amount-of-items">Amount of items to buy: <%= @shopping_list[:total_items] %></p>
<p class="total-value">Total Value of food needed: $ <%= @shopping_list[:total_value] %></p>

<table>
  <thead>
    <tr class="tr-head">
      <th>Food</th>
      <th>Quantity</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @shopping_list[:shopping_list].each do |food_name, data| %>
      <tr class="tr-list li">
        <td class="food-name"><%= food_name %></td>        
        <td class="food-quantity"><%= data[:quantity] %></td>
        <td class="food-price">$<%= data[:price] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<h2>List of all users:</h2>
<ul class= "users-index-ul">
  <% @users.each do |u| %>
    <li class= "users-index-li li"><%= u.name %></li>
  <% end %>
</ul>